name: Update Composer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-composer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Composer
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          php -r "unlink('composer-setup.php');"
        
      - name: Update Composer dependencies
        run: composer update --no-progress --no-interaction

      - name: Commit changes
        run: |
          git config --global user.email "aa2021071075@virtual.upt.pe"
          git config --global user.name "AlbertApaza"
          git add composer.lock
          git commit -m "Update Composer dependencies"
          git push
